package org.ianswitzer.itemhuntv3.managers;

import org.bukkit.Axis;
import org.bukkit.Material;
import org.bukkit.Statistic;
import org.bukkit.advancement.Advancement;
import org.bukkit.advancement.AdvancementDisplayType;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.EntityType;
import org.bukkit.event.entity.EntityDamageEvent;
import org.bukkit.potion.PotionEffectType;
import org.checkerframework.checker.units.qual.A;
import org.ianswitzer.itemhuntv3.interfaces.GenericTask;
import org.ianswitzer.itemhuntv3.tasks.*;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Random;

public class TaskManager {
    private HashMap<Integer,ArrayList<GenericTask>> tasks;
    private final Random random;

    public TaskManager() {
        random = new Random();
        init();
    }

    public GenericTask getRandomTask(int round) {
        ArrayList<GenericTask> options = tasks.get(round);
        return options.get(random.nextInt(options.size()));
    }

    public ArrayList<StatTask> getAllStatistics() {
        ArrayList<StatTask> list = new ArrayList<>();
        for (int key : tasks.keySet()) {
            for (GenericTask task : tasks.get(key)) {
                if (task instanceof StatTask) list.add((StatTask) task);
            }
        }
        return list;
    }

    public void resetCauseOfDeathCompletion() {
        for (int key : tasks.keySet()) {
            for (GenericTask task : tasks.get(key)) {
                if (task instanceof CauseOfDeathTask) ((CauseOfDeathTask) task).resetCompletion();
            }
        }
    }

    private void addTask(int tier, int weight, GenericTask task) {
        if (tasks == null) tasks = new HashMap<>();
        tasks.computeIfAbsent(tier, k -> new ArrayList<>());
        for (int i = 0; i < weight; i++) {
            tasks.get(tier).add(task);
        }
    }

    private void init() {
        // Round 1
        addTask(1, 1, new ItemTask(Material.WOODEN_HOE));
        addTask(1, 1, new ItemTask(Material.WOODEN_AXE));
        addTask(1, 1, new ItemTask(Material.WOODEN_PICKAXE));
        addTask(1, 1, new ItemTask(Material.WOODEN_SHOVEL));
        addTask(1, 1, new ItemTask(Material.WOODEN_SWORD));
        addTask(1, 1, new ItemTask(Material.STONE_PICKAXE));
        addTask(1, 1, new ItemTask(Material.STONE_AXE));
        addTask(1, 1, new ItemTask(Material.STONE_SWORD));
        addTask(1, 1, new ItemTask(Material.STONE_SHOVEL));
        addTask(1, 1, new ItemTask(Material.STONE_HOE));
        addTask(1, 1, new ItemTask(Material.CRAFTING_TABLE));
        addTask(1, 1, new ItemTask(Material.FURNACE));
        addTask(1, 1, new ItemTask(Material.STICK));
        addTask(1, 1, new ItemTask(Material.DIRT));
        addTask(1, 1, new ItemTask(Material.SAND));
        addTask(1, 1, new ItemTask(Material.GRAVEL));
        addTask(1, 1, new ItemTask(Material.CLAY_BALL));
        addTask(1, 1, new ItemTask(Material.COBBLESTONE_SLAB));
        addTask(1, 1, new ItemTask(Material.COBBLESTONE_WALL));
        addTask(1, 1, new ItemTask(Material.COBBLESTONE_STAIRS));
        addTask(1, 1, new ItemTask(Material.WHEAT_SEEDS));
        addTask(1, 1, new ItemTask(Material.LADDER));
        addTask(1, 1, new ItemTask(Material.LEVER));
        addTask(1, 1, new ItemTask(Material.OAK_PRESSURE_PLATE));
        addTask(1, 1, new ItemTask(Material.OAK_TRAPDOOR));
        addTask(1, 1, new ItemTask(Material.OAK_BUTTON));
        addTask(1, 1, new ItemTask(Material.OAK_FENCE));
        addTask(1, 1, new ItemTask(Material.OAK_FENCE_GATE));
        addTask(1, 1, new ItemTask(Material.OAK_LOG));
        addTask(1, 1, new ItemTask(Material.OAK_PLANKS));
        addTask(1, 1, new ItemTask(Material.CHARCOAL));
        addTask(1, 1, new ItemTask(Material.COMPOSTER));
        addTask(1, 1, new ItemTask(Material.BARREL));
        addTask(1, 1, new ItemTask(Material.CHEST));
        addTask(1, 1, new ItemTask(Material.BOWL));
        addTask(1, 3, new StatTask(Statistic.OPEN_BARREL, 10));
        addTask(1, 3, new StatTask(Statistic.CHEST_OPENED, 10));
        addTask(1, 3, new StatTask(Statistic.CLIMB_ONE_CM, 1000));
        addTask(1, 3, new StatTask(Statistic.SWIM_ONE_CM, 1000));
        addTask(1, 3, new StatTask(Statistic.JUMP, 50));
        addTask(1, 3, new StatTask(Statistic.CRAFTING_TABLE_INTERACTION, 25));
        addTask(1, 3, new StatTask(Statistic.DEATHS, 1));
        addTask(1, 3, new StatTask(Statistic.DAMAGE_TAKEN, 2000));
        addTask(1, 3, new AdvancementTask("story/mine_stone"));
        addTask(1, 3, new AdvancementTask("story/upgrade_tools"));
        addTask(1, 3, new LocationTask(Axis.Y, 50, false));
        addTask(1, 3, new CauseOfDeathTask(EntityDamageEvent.DamageCause.FALL));
        addTask(1, 3, new CauseOfDeathTask(EntityDamageEvent.DamageCause.SUFFOCATION));
        addTask(1, 3, new CauseOfDeathTask(EntityDamageEvent.DamageCause.DROWNING));
        // Round 2
        addTask(2, 1, new ItemTask(Material.TORCH));
        addTask(2, 1, new ItemTask(Material.STONE));
        addTask(2, 1, new ItemTask(Material.STONE_BRICKS));
        addTask(2, 1, new ItemTask(Material.STONE_BRICK_SLAB));
        addTask(2, 1, new ItemTask(Material.STONE_BRICK_STAIRS));
        addTask(2, 1, new ItemTask(Material.STONE_BUTTON));
        addTask(2, 1, new ItemTask(Material.STONE_PRESSURE_PLATE));
        addTask(2, 1, new ItemTask(Material.COAL));
        addTask(2, 1, new ItemTask(Material.IRON_INGOT));
        addTask(2, 1, new ItemTask(Material.IRON_NUGGET));
        addTask(2, 1, new ItemTask(Material.RAW_IRON));
        addTask(2, 1, new ItemTask(Material.TRIPWIRE_HOOK));
        addTask(2, 1, new ItemTask(Material.SMOKER));
        addTask(2, 1, new ItemTask(Material.GRANITE));
        addTask(2, 1, new ItemTask(Material.DIORITE));
        addTask(2, 1, new ItemTask(Material.ANDESITE));
        addTask(2, 1, new ItemTask(Material.IRON_AXE));
        addTask(2, 1, new ItemTask(Material.IRON_HOE));
        addTask(2, 1, new ItemTask(Material.IRON_SHOVEL));
        addTask(2, 1, new ItemTask(Material.IRON_SWORD));
        addTask(2, 1, new ItemTask(Material.IRON_PICKAXE));
        addTask(2, 1, new ItemTask(Material.BRICK));
        addTask(2, 1, new ItemTask(Material.BRICKS));
        addTask(2, 1, new ItemTask(Material.FLOWER_POT));
        addTask(2, 1, new ItemTask(Material.SHIELD));
        addTask(2, 1, new ItemTask(Material.SHEARS));
        addTask(2, 1, new ItemTask(Material.FLINT_AND_STEEL));
        addTask(2, 1, new ItemTask(Material.FLINT));
        addTask(2, 1, new ItemTask(Material.FLETCHING_TABLE));
        addTask(2, 1, new ItemTask(Material.SMITHING_TABLE));
        addTask(2, 1, new ItemTask(Material.GLASS));
        addTask(2, 1, new ItemTask(Material.GLASS_BOTTLE));
        addTask(2, 1, new ItemTask(Material.LEATHER));
        addTask(2, 1, new ItemTask(Material.FEATHER));
        addTask(2, 1, new ItemTask(Material.COD));
        addTask(2, 1, new ItemTask(Material.CHICKEN));
        addTask(2, 1, new ItemTask(Material.COOKED_CHICKEN));
        addTask(2, 1, new ItemTask(Material.COOKED_COD));
        addTask(2, 1, new ItemTask(Material.GRINDSTONE));
        addTask(2, 1, new ItemTask(Material.BEEF));
        addTask(2, 1, new ItemTask(Material.COOKED_BEEF));
        addTask(2, 1, new ItemTask(Material.WATER_BUCKET));
        addTask(2, 1, new ItemTask(Material.BUCKET));
        addTask(2, 1, new ItemTask(Material.SUGAR));
        addTask(2, 1, new ItemTask(Material.SUGAR_CANE));
        addTask(2, 1, new ItemTask(Material.PAPER));
        addTask(2, 1, new ItemTask(Material.CAMPFIRE));
        addTask(2, 5, new LocationTask(Axis.Y, 150, true));
        addTask(2, 3, new StatTask(Statistic.SPRINT_ONE_CM, 10000));
        addTask(2, 3, new StatTask(Statistic.CROUCH_ONE_CM, 5000));
        addTask(2, 3, new StatTask(Statistic.KILL_ENTITY, EntityType.COW, 5));
        addTask(2, 3, new StatTask(Statistic.KILL_ENTITY, EntityType.CHICKEN, 5));
        addTask(2, 3, new StatTask(Statistic.KILL_ENTITY, EntityType.SHEEP, 5));
        addTask(2, 3, new StatTask(Statistic.KILL_ENTITY, EntityType.PIG, 5));
        addTask(2, 3, new StatTask(Statistic.DEATHS, 5));
        addTask(2, 3, new AdvancementTask("story/smelt_iron"));
        addTask(2, 3, new StatTask(Statistic.DAMAGE_TAKEN, 5000));
        addTask(2, 3, new CauseOfDeathTask(EntityDamageEvent.DamageCause.FIRE_TICK));
        // Round 3
        addTask(3, 1, new PotionEffectTask(PotionEffectType.HUNGER));
        addTask(3, 1, new PotionEffectTask(PotionEffectType.DOLPHINS_GRACE));
        addTask(3, 5, new LocationTask(Axis.Y, 225, true));
        addTask(3, 5, new LocationTask(Axis.Y, 15, false));
        addTask(3, 1, new ItemTask(Material.CAULDRON));
        addTask(3, 1, new ItemTask(Material.COOKED_PORKCHOP));
        addTask(3, 1, new ItemTask(Material.WHITE_WOOL));
        addTask(3, 1, new ItemTask(Material.BLACK_WOOL));
        addTask(3, 1, new ItemTask(Material.WHITE_CONCRETE));
        addTask(3, 1, new ItemTask(Material.WHITE_CONCRETE_POWDER));
        addTask(3, 1, new ItemTask(Material.LANTERN));
        addTask(3, 1, new ItemTask(Material.OAK_LEAVES));
        addTask(3, 1, new ItemTask(Material.BIRCH_LEAVES));
        addTask(3, 1, new ItemTask(Material.RED_CARPET));
        addTask(3, 1, new ItemTask(Material.YELLOW_WOOL));
        addTask(3, 1, new ItemTask(Material.ORANGE_WOOL));
        addTask(3, 1, new ItemTask(Material.RED_STAINED_GLASS));
        addTask(3, 1, new ItemTask(Material.WHITE_BED));
        addTask(3, 1, new ItemTask(Material.RAIL));
        addTask(3, 1, new ItemTask(Material.BONE));
        addTask(3, 1, new ItemTask(Material.STRING));
        addTask(3, 1, new ItemTask(Material.ARROW));
        addTask(3, 1, new ItemTask(Material.SPIDER_EYE));
        addTask(3, 1, new ItemTask(Material.WHITE_DYE));
        addTask(3, 1, new ItemTask(Material.GUNPOWDER));
        addTask(3, 1, new ItemTask(Material.ROTTEN_FLESH));
        addTask(3, 1, new ItemTask(Material.ARMOR_STAND));
        addTask(3, 1, new ItemTask(Material.CHEST_MINECART));
        addTask(3, 1, new ItemTask(Material.FURNACE_MINECART));
        addTask(3, 1, new ItemTask(Material.HOPPER));
        addTask(3, 1, new ItemTask(Material.MINECART));
        addTask(3, 1, new ItemTask(Material.LEATHER_BOOTS));
        addTask(3, 1, new ItemTask(Material.LEATHER_HELMET));
        addTask(3, 1, new ItemTask(Material.LEATHER_CHESTPLATE));
        addTask(3, 1, new ItemTask(Material.LEATHER_LEGGINGS));
        addTask(3, 1, new ItemTask(Material.ITEM_FRAME));
        addTask(3, 1, new ItemTask(Material.RAW_COPPER));
        addTask(3, 1, new ItemTask(Material.COPPER_INGOT));
        addTask(3, 1, new ItemTask(Material.HEAVY_WEIGHTED_PRESSURE_PLATE));
        addTask(3, 1, new ItemTask(Material.IRON_BARS));
        addTask(3, 1, new ItemTask(Material.IRON_TRAPDOOR));
        addTask(3, 1, new ItemTask(Material.IRON_BOOTS));
        addTask(3, 1, new ItemTask(Material.IRON_HELMET));
        addTask(3, 1, new ItemTask(Material.BOOK));
        addTask(3, 1, new ItemTask(Material.CHAIN));
        addTask(3, 3, new StatTask(Statistic.DEATHS, 20));
        addTask(3, 3, new StatTask(Statistic.KILL_ENTITY, EntityType.COW, 10));
        addTask(3, 3, new StatTask(Statistic.KILL_ENTITY, EntityType.SHEEP, 10));
        addTask(3, 3, new StatTask(Statistic.KILL_ENTITY, EntityType.PIG, 10));
        addTask(3, 3, new StatTask(Statistic.KILL_ENTITY, EntityType.CHICKEN, 10));
        addTask(3, 3, new StatTask(Statistic.KILL_ENTITY, EntityType.SKELETON, 2));
        addTask(3, 3, new StatTask(Statistic.KILL_ENTITY, EntityType.ZOMBIE, 2));
        addTask(3, 3, new StatTask(Statistic.KILL_ENTITY, EntityType.SPIDER, 2));
        addTask(3, 3, new StatTask(Statistic.KILL_ENTITY, EntityType.CREEPER, 2));
        addTask(3, 3, new StatTask(Statistic.DAMAGE_TAKEN, 20000));
        addTask(3, 3, new CauseOfDeathTask(EntityDamageEvent.DamageCause.PROJECTILE));
        addTask(3, 3, new CauseOfDeathTask(EntityDamageEvent.DamageCause.ENTITY_ATTACK));
        // Round 4
        addTask(4, 1, new ItemTask(Material.RAW_GOLD));
        addTask(4, 1, new ItemTask(Material.GOLD_INGOT));
        addTask(4, 1, new ItemTask(Material.RAW_COPPER_BLOCK));
        addTask(4, 1, new ItemTask(Material.DEEPSLATE));
        addTask(4, 1, new ItemTask(Material.MILK_BUCKET));
        addTask(4, 1, new ItemTask(Material.COBBLED_DEEPSLATE));
        addTask(4, 1, new ItemTask(Material.DEEPSLATE_BRICKS));
        addTask(4, 1, new ItemTask(Material.COPPER_BLOCK));
        addTask(4, 1, new ItemTask(Material.HEAVY_WEIGHTED_PRESSURE_PLATE));
        addTask(4, 1, new ItemTask(Material.LIGHT_WEIGHTED_PRESSURE_PLATE));
        addTask(4, 1, new ItemTask(Material.APPLE));
        addTask(4, 1, new ItemTask(Material.IRON_CHESTPLATE));
        addTask(4, 1, new ItemTask(Material.IRON_LEGGINGS));
        addTask(4, 1, new ItemTask(Material.IRON_BLOCK));
        addTask(4, 1, new ItemTask(Material.GOLDEN_HOE));
        addTask(4, 1, new ItemTask(Material.GOLDEN_AXE));
        addTask(4, 1, new ItemTask(Material.GOLDEN_PICKAXE));
        addTask(4, 1, new ItemTask(Material.DRIED_KELP_BLOCK));
        addTask(4, 1, new ItemTask(Material.BLACK_CONCRETE));
        addTask(4, 1, new ItemTask(Material.ORANGE_BED));
        addTask(4, 1, new ItemTask(Material.BOW));
        addTask(4, 1, new ItemTask(Material.FISHING_ROD));
        addTask(4, 1, new ItemTask(Material.GUNPOWDER));
        addTask(4, 1, new ItemTask(Material.BLUE_WOOL));
        addTask(4, 1, new ItemTask(Material.BLUE_DYE));
        addTask(4, 1, new ItemTask(Material.LIGHT_BLUE_DYE));
        addTask(4, 1, new ItemTask(Material.CROSSBOW));
        addTask(4, 1, new ItemTask(Material.ORANGE_CONCRETE));
        addTask(4, 1, new ItemTask(Material.BOOKSHELF));
        addTask(4, 1, new ItemTask(Material.DRIED_KELP));
        addTask(4, 1, new ItemTask(Material.DRIED_KELP_BLOCK));
        addTask(4, 5, new LocationTask(Axis.Y, 300, true));
        addTask(4, 5, new LocationTask(Axis.Y, -32, false));
        addTask(4, 3, new LocationTask(Axis.X, 1000, true));
        addTask(4, 3, new LocationTask(Axis.Z, 1000, true));
        addTask(4, 3, new LocationTask(Axis.X, -1000, false));
        addTask(4, 3, new LocationTask(Axis.Z, -1000, false));
        addTask(4, 5, new StatTask(Statistic.ANIMALS_BRED, 5));
        addTask(4, 5, new StatTask(Statistic.CAULDRON_FILLED, 3));
        addTask(4, 3, new StatTask(Statistic.ENTITY_KILLED_BY, EntityType.CREEPER, 2));
        addTask(4, 3, new StatTask(Statistic.ENTITY_KILLED_BY, EntityType.ZOMBIE, 2));
        addTask(4, 3, new StatTask(Statistic.ENTITY_KILLED_BY, EntityType.SKELETON, 2));
        addTask(4, 3, new StatTask(Statistic.ENTITY_KILLED_BY, EntityType.SPIDER, 2));
        addTask(4, 3, new CauseOfDeathTask(EntityDamageEvent.DamageCause.ENTITY_EXPLOSION));
        addTask(4, 3, new CauseOfDeathTask(EntityDamageEvent.DamageCause.LAVA));
        // Round 5
        addTask(5, 1, new ItemTask(Material.PINK_WOOL));
        addTask(5, 1, new ItemTask(Material.PINK_BED));
        addTask(5, 1, new ItemTask(Material.LAPIS_LAZULI));
        addTask(5, 1, new ItemTask(Material.LAPIS_BLOCK));
        addTask(5, 1, new ItemTask(Material.REDSTONE));
        addTask(5, 1, new ItemTask(Material.ANVIL));
        addTask(5, 1, new ItemTask(Material.EGG));
        addTask(5, 1, new ItemTask(Material.FIREWORK_ROCKET));
        addTask(5, 1, new ItemTask(Material.BLAST_FURNACE));
        addTask(5, 1, new ItemTask(Material.MAGMA_BLOCK));
        addTask(5, 1, new ItemTask(Material.BLUE_CONCRETE));
        addTask(5, 1, new ItemTask(Material.RED_MUSHROOM));
        addTask(5, 1, new ItemTask(Material.BROWN_MUSHROOM));
        addTask(5, 1, new ItemTask(Material.WRITABLE_BOOK));
        addTask(5, 1, new ItemTask(Material.HAY_BLOCK));
        addTask(5, 1, new ItemTask(Material.SPIDER_EYE));
        addTask(5, 1, new ItemTask(Material.TROPICAL_FISH));
        addTask(5, 1, new ItemTask(Material.COD_BUCKET));
        addTask(5, 1, new ItemTask(Material.SALMON_BUCKET));
        addTask(5, 1, new ItemTask(Material.FERMENTED_SPIDER_EYE));
        addTask(5, 5, new LocationTask(Axis.Y, 300, true));
        addTask(5, 5, new LocationTask(Axis.Y, -60, false));
        addTask(5, 3, new LocationTask(Axis.X, 1000, true));
        addTask(5, 3, new LocationTask(Axis.Z, 1000, true));
        addTask(5, 3, new LocationTask(Axis.X, -1000, false));
        addTask(5, 3, new LocationTask(Axis.Z, -1000, false));
        addTask(5, 3, new AdvancementTask("adventure/summon_iron_golem"));
        addTask(5, 3, new StatTask(Statistic.ENTITY_KILLED_BY, EntityType.DROWNED, 1));
        addTask(5, 3, new StatTask(Statistic.DAMAGE_TAKEN, 500));
        addTask(5, 3, new StatTask(Statistic.MINECART_ONE_CM, 5000));
        // Round 6
        addTask(6, 1, new ItemTask(Material.GLOW_INK_SAC));
        addTask(6, 1, new ItemTask(Material.LILY_PAD));
        addTask(6, 1, new ItemTask(Material.CARROT));
        addTask(6, 1, new ItemTask(Material.CARROT_ON_A_STICK));
        addTask(6, 1, new ItemTask(Material.TNT));
        addTask(6, 1, new ItemTask(Material.TNT_MINECART));
        addTask(6, 1, new ItemTask(Material.GOLD_BLOCK));
        addTask(6, 1, new ItemTask(Material.RAW_GOLD_BLOCK));
        addTask(6, 1, new ItemTask(Material.HONEY_BOTTLE));
        addTask(6, 1, new ItemTask(Material.BLUE_GLAZED_TERRACOTTA));
        addTask(6, 1, new ItemTask(Material.REDSTONE_LAMP));
        addTask(6, 1, new ItemTask(Material.CARROT_ON_A_STICK));
        addTask(6, 1, new ItemTask(Material.REDSTONE));
        addTask(6, 1, new ItemTask(Material.REDSTONE_BLOCK));
        addTask(6, 1, new ItemTask(Material.REDSTONE_TORCH));
        addTask(6, 1, new ItemTask(Material.COMPASS));
        addTask(6, 1, new ItemTask(Material.MAP));
        addTask(6, 1, new ItemTask(Material.PISTON));
        addTask(6, 1, new ItemTask(Material.SHROOMLIGHT));
        addTask(6, 1, new ItemTask(Material.SOUL_SAND));
        addTask(6, 1, new ItemTask(Material.SOUL_TORCH));
        addTask(6, 1, new ItemTask(Material.NETHERRACK));
        addTask(6, 1, new ItemTask(Material.SOUL_SOIL));
        addTask(6, 1, new ItemTask(Material.WARPED_DOOR));
        addTask(6, 1, new ItemTask(Material.CRIMSON_DOOR));
        addTask(6, 1, new ItemTask(Material.WARPED_STEM));
        addTask(6, 1, new ItemTask(Material.STRIPPED_WARPED_HYPHAE));
        addTask(6, 1, new ItemTask(Material.CRIMSON_STEM));
        addTask(6, 1, new ItemTask(Material.STRIPPED_CRIMSON_HYPHAE));
        addTask(6, 1, new ItemTask(Material.CLOCK));
        addTask(6, 1, new ItemTask(Material.DISPENSER));
        addTask(6, 1, new ItemTask(Material.DROPPER));
        addTask(6, 1, new ItemTask(Material.ACTIVATOR_RAIL));
        addTask(6, 1, new ItemTask(Material.POWERED_RAIL));
        addTask(6, 1, new ItemTask(Material.SOUL_LANTERN));
        addTask(6, 1, new ItemTask(Material.BASALT));
        addTask(6, 1, new ItemTask(Material.QUARTZ_BLOCK));
        addTask(6, 1, new ItemTask(Material.DAYLIGHT_DETECTOR));
        addTask(6, 1, new ItemTask(Material.PUMPKIN));
        addTask(6, 1, new ItemTask(Material.PUMPKIN_SEEDS));
        addTask(6, 1, new ItemTask(Material.JACK_O_LANTERN));
        addTask(6, 1, new ItemTask(Material.GLOWSTONE));
        addTask(6, 1, new ItemTask(Material.NOTE_BLOCK));
        addTask(6, 1, new ItemTask(Material.NETHER_BRICK));
        addTask(6, 1, new ItemTask(Material.FIRE_CHARGE));
        addTask(6, 1, new ItemTask(Material.MAGMA_BLOCK));
        addTask(6, 1, new ItemTask(Material.MUSHROOM_STEW));
        addTask(6, 1, new ItemTask(Material.JACK_O_LANTERN));
        addTask(6, 1, new ItemTask(Material.PUFFERFISH));
        addTask(6, 1, new PotionEffectTask(PotionEffectType.POISON));
        addTask(6, 1, new PotionEffectTask(PotionEffectType.FIRE_RESISTANCE));
        addTask(6, 1, new PotionEffectTask(PotionEffectType.JUMP));
        addTask(6, 1, new PotionEffectTask(PotionEffectType.BLINDNESS));
        addTask(6, 1, new PotionEffectTask(PotionEffectType.REGENERATION));
        addTask(6, 1, new PotionEffectTask(PotionEffectType.NIGHT_VISION));
        addTask(6, 1, new PotionEffectTask(PotionEffectType.WEAKNESS));
        addTask(6, 5, new LocationTask(Axis.Y, 320, true));
        addTask(6, 5, new LocationTask(Axis.Y, -60, false));
        addTask(6, 3, new StatTask(Statistic.TARGET_HIT, 1));
        addTask(6, 3, new StatTask(Statistic.NOTEBLOCK_TUNED, 50));
        addTask(6, 3, new StatTask(Statistic.FISH_CAUGHT, 10));
        addTask(6, 3, new AdvancementTask("story/enter_the_nether"));
        addTask(6, 3, new StatTask(Statistic.ENTITY_KILLED_BY, EntityType.PIGLIN, 1));
        addTask(6, 3, new StatTask(Statistic.ENTITY_KILLED_BY, EntityType.ZOMBIFIED_PIGLIN, 1));
        addTask(6, 3, new StatTask(Statistic.KILL_ENTITY, EntityType.PIGLIN, 5));
        addTask(6, 3, new StatTask(Statistic.KILL_ENTITY, EntityType.ZOMBIFIED_PIGLIN, 5));
        addTask(6, 3, new CauseOfDeathTask(EntityDamageEvent.DamageCause.HOT_FLOOR));
        addTask(6, 3, new CauseOfDeathTask(EntityDamageEvent.DamageCause.FALLING_BLOCK));
        // Round 7
        addTask(7, 1, new ItemTask(Material.ENDER_PEARL));
        addTask(7, 1, new ItemTask(Material.BELL));
        addTask(7, 1, new ItemTask(Material.PUMPKIN_PIE));
        addTask(7, 1, new ItemTask(Material.WARPED_FUNGUS_ON_A_STICK));
        addTask(7, 1, new ItemTask(Material.MELON_SLICE));
        addTask(7, 1, new ItemTask(Material.MELON_SEEDS));
        addTask(7, 1, new ItemTask(Material.MELON));
        addTask(7, 1, new ItemTask(Material.BLAZE_POWDER));
        addTask(7, 1, new ItemTask(Material.BLAZE_ROD));
        addTask(7, 1, new ItemTask(Material.NETHER_WART));
        addTask(7, 1, new ItemTask(Material.GOLDEN_APPLE));
        addTask(7, 1, new ItemTask(Material.DIAMOND));
        addTask(7, 1, new ItemTask(Material.DIAMOND_PICKAXE));
        addTask(7, 1, new ItemTask(Material.DIAMOND_AXE));
        addTask(7, 1, new ItemTask(Material.DIAMOND_SHOVEL));
        addTask(7, 1, new ItemTask(Material.DIAMOND_HOE));
        addTask(7, 1, new ItemTask(Material.JUKEBOX));
        addTask(7, 1, new ItemTask(Material.EMERALD));
        addTask(7, 1, new ItemTask(Material.ENDER_EYE));
        addTask(7, 1, new ItemTask(Material.GOLDEN_CARROT));
        addTask(7, 1, new ItemTask(Material.POISONOUS_POTATO));
        addTask(7, 1, new ItemTask(Material.BLACKSTONE));
        addTask(7, 1, new ItemTask(Material.POLISHED_BLACKSTONE));
        addTask(7, 1, new ItemTask(Material.GLISTERING_MELON_SLICE));
        addTask(7, 1, new ItemTask(Material.SNOW_BLOCK));
        addTask(7, 1, new ItemTask(Material.MAGMA_CREAM));
        addTask(7, 1, new ItemTask(Material.SPECTRAL_ARROW));
        addTask(7, 1, new ItemTask(Material.POINTED_DRIPSTONE));
        addTask(7, 1, new ItemTask(Material.COMPARATOR));
        addTask(7, 1, new ItemTask(Material.OBSERVER));
        addTask(7, 1, new ItemTask(Material.OBSIDIAN));
        addTask(7, 1, new ItemTask(Material.CAKE));
        addTask(7, 1, new ItemTask(Material.GLOW_BERRIES));
        addTask(7, 1, new ItemTask(Material.GLOW_INK_SAC));
        addTask(7, 1, new ItemTask(Material.BREWING_STAND));
        addTask(7, 1, new PotionEffectTask(PotionEffectType.WITHER));
        addTask(7, 1, new PotionEffectTask(PotionEffectType.GLOWING));
        addTask(7, 1, new PotionEffectTask(PotionEffectType.ABSORPTION));
        addTask(7, 3, new StatTask(Statistic.BELL_RING, 1));
        addTask(7, 5, new StatTask(Statistic.MOB_KILLS, 150));
        addTask(7, 3, new AdvancementTask("story/mine_diamond"));
        addTask(7, 3, new AdvancementTask("story/form_obsidian"));
        addTask(7, 3, new CauseOfDeathTask(EntityDamageEvent.DamageCause.FREEZE));
        addTask(7, 3, new CauseOfDeathTask(EntityDamageEvent.DamageCause.CONTACT));
        addTask(7, 3, new CauseOfDeathTask(EntityDamageEvent.DamageCause.WITHER));
        // Round 8
        addTask(8, 1, new ItemTask(Material.PRISMARINE));
        addTask(8, 1, new ItemTask(Material.PRISMARINE_SHARD));
        addTask(8, 1, new ItemTask(Material.DARK_PRISMARINE));
        addTask(8, 1, new ItemTask(Material.SEA_LANTERN));
        addTask(8, 1, new ItemTask(Material.SPONGE));
        addTask(8, 1, new ItemTask(Material.WET_SPONGE));
        addTask(8, 1, new ItemTask(Material.GILDED_BLACKSTONE));
        addTask(8, 1, new ItemTask(Material.BLACKSTONE_WALL));
        addTask(8, 1, new ItemTask(Material.ENCHANTING_TABLE));
        addTask(8, 1, new ItemTask(Material.SADDLE));
        addTask(8, 1, new ItemTask(Material.NAME_TAG));
        addTask(8, 1, new ItemTask(Material.RABBIT_HIDE));
        addTask(8, 1, new ItemTask(Material.COBWEB));
        addTask(8, 1, new ItemTask(Material.RESPAWN_ANCHOR));
        addTask(8, 1, new ItemTask(Material.CRYING_OBSIDIAN));
        addTask(8, 1, new PotionEffectTask(PotionEffectType.SLOW_DIGGING));
        addTask(8, 1, new PotionEffectTask(PotionEffectType.INCREASE_DAMAGE));
        addTask(8, 1, new PotionEffectTask(PotionEffectType.INVISIBILITY));
        addTask(8, 3, new EnchantmentTask(Enchantment.DAMAGE_ALL, Material.DIAMOND_SWORD));
        addTask(8, 3, new EnchantmentTask(Enchantment.PROTECTION_ENVIRONMENTAL, Material.ENCHANTED_BOOK));
        // Round 9
        addTask(9, 1, new ItemTask(Material.DEAD_BRAIN_CORAL));
        addTask(9, 1, new ItemTask(Material.SEA_PICKLE));
        addTask(9, 1, new ItemTask(Material.LEAD));
        addTask(9, 1, new ItemTask(Material.STICKY_PISTON));
        addTask(9, 1, new ItemTask(Material.ENDER_CHEST));
        addTask(9, 1, new ItemTask(Material.DIAMOND_BLOCK));
        addTask(9, 1, new ItemTask(Material.EMERALD_BLOCK));
        addTask(9, 1, new ItemTask(Material.GHAST_TEAR));
        addTask(9, 1, new ItemTask(Material.COOKIE));
        addTask(9, 1, new ItemTask(Material.JUNGLE_SAPLING));
        addTask(9, 1, new ItemTask(Material.RESPAWN_ANCHOR));
        addTask(9, 1, new ItemTask(Material.BAMBOO));
        addTask(9, 1, new ItemTask(Material.SCAFFOLDING));
        addTask(9, 1, new ItemTask(Material.DIAMOND_HORSE_ARMOR));
        addTask(9, 1, new ItemTask(Material.GOLDEN_HORSE_ARMOR));
        addTask(9, 1, new ItemTask(Material.IRON_HORSE_ARMOR));
        addTask(9, 1, new ItemTask(Material.RABBIT_FOOT));
        addTask(9, 1, new ItemTask(Material.EXPERIENCE_BOTTLE));
        addTask(9, 1, new ItemTask(Material.HEART_OF_THE_SEA));
        addTask(9, 1, new ItemTask(Material.NAUTILUS_SHELL));
        addTask(9, 1, new ItemTask(Material.END_CRYSTAL));
        addTask(9, 1, new ItemTask(Material.GRASS_BLOCK));
        addTask(9, 1, new ItemTask(Material.SPYGLASS));
        addTask(9, 1, new ItemTask(Material.ANCIENT_DEBRIS));
        addTask(9, 1, new ItemTask(Material.NETHERITE_SCRAP));
        addTask(9, 1, new ItemTask(Material.ORANGE_CANDLE));
        addTask(9, 1, new ItemTask(Material.HONEYCOMB_BLOCK));
        addTask(9, 1, new ItemTask(Material.HONEY_BLOCK));
        addTask(9, 1, new ItemTask(Material.WAXED_CUT_COPPER_STAIRS));
        addTask(9, 1, new PotionEffectTask(PotionEffectType.BAD_OMEN));
        addTask(9, 1, new EnchantmentTask(Enchantment.DAMAGE_ALL, Material.DIAMOND_AXE));
        // Round 10
        addTask(10, 1, new ItemTask(Material.ICE));
        addTask(10, 1, new ItemTask(Material.ECHO_SHARD));
        addTask(10, 1, new ItemTask(Material.DISC_FRAGMENT_5));
        addTask(10, 1, new ItemTask(Material.BLUE_ICE));
        addTask(10, 1, new ItemTask(Material.PACKED_ICE));
        addTask(10, 1, new ItemTask(Material.SLIME_BLOCK));
        addTask(10, 1, new ItemTask(Material.SLIME_BALL));
        addTask(10, 1, new ItemTask(Material.COAL_ORE));
        addTask(10, 1, new ItemTask(Material.MUSIC_DISC_PIGSTEP));
        addTask(10, 1, new ItemTask(Material.BROWN_CANDLE));
        addTask(10, 1, new ItemTask(Material.TRIDENT));
        addTask(10, 1, new ItemTask(Material.DEEPSLATE_REDSTONE_ORE));
        addTask(10, 1, new ItemTask(Material.DEEPSLATE_DIAMOND_ORE));
        addTask(10, 1, new ItemTask(Material.DEEPSLATE_LAPIS_ORE));
        addTask(10, 1, new ItemTask(Material.DEEPSLATE_GOLD_ORE));
        addTask(10, 1, new ItemTask(Material.DEEPSLATE_IRON_ORE));
        addTask(10, 1, new ItemTask(Material.END_STONE));
        addTask(10, 1, new ItemTask(Material.WITHER_SKELETON_SKULL));
        addTask(10, 1, new ItemTask(Material.NETHER_GOLD_ORE));
        addTask(10, 1, new ItemTask(Material.NETHER_QUARTZ_ORE));
        addTask(10, 1, new ItemTask(Material.LODESTONE));
        addTask(10, 1, new ItemTask(Material.NETHERITE_HOE));
        addTask(10, 1, new ItemTask(Material.NETHERITE_INGOT));
        addTask(10, 1, new ItemTask(Material.CHAINMAIL_CHESTPLATE));
        addTask(10, 1, new ItemTask(Material.ENCHANTED_GOLDEN_APPLE));
        addTask(10, 1, new ItemTask(Material.DRAGON_BREATH));
        addTask(10, 1, new ItemTask(Material.TOTEM_OF_UNDYING));
        addTask(10, 1, new ItemTask(Material.NETHERITE_UPGRADE_SMITHING_TEMPLATE));
        addTask(10, 1, new PotionEffectTask(PotionEffectType.HERO_OF_THE_VILLAGE));
        addTask(10, 1, new PotionEffectTask(PotionEffectType.DAMAGE_RESISTANCE));
        addTask(10, 1, new LocationTask(Axis.X, 20000, true));
        addTask(10, 1, new LocationTask(Axis.Z, 20000, true));
        addTask(10, 1, new LocationTask(Axis.X, -20000, false));
        addTask(10, 1, new LocationTask(Axis.Z, -20000, false));
        addTask(10, 5, new LocationTask(Axis.Y, 325, true));
        addTask(10, 3, new AdvancementTask("story/cure_zombie_villager"));
        addTask(10, 3, new StatTask(Statistic.ENTITY_KILLED_BY, EntityType.ENDER_DRAGON, 1));
        addTask(10, 1, new EnchantmentTask(Enchantment.SILK_TOUCH, Material.DIAMOND_HOE));
        addTask(10, 3, new CauseOfDeathTask(EntityDamageEvent.DamageCause.VOID));
        addTask(10, 3, new CauseOfDeathTask(EntityDamageEvent.DamageCause.THORNS));
        addTask(10, 3, new CauseOfDeathTask(EntityDamageEvent.DamageCause.SONIC_BOOM));
    }
}
