name: ItemHuntV3
version: '${version}'
main: org.ianswitzer.itemhuntv3.ItemHuntV3
api-version: '1.20'
commands:
  itemhunt:
    description: Start/stop/join/manage an Item Hunt
    usage: /itemhunt <start/stop/clear/join/reroll/shuffle/extend/setskipcount>